// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProject'](arg1, arg2, arg3);
}

export function AddServer(arg1, arg2) {
  return window['go']['main']['App']['AddServer'](arg1, arg2);
}

export function AnalyzeProject(arg1) {
  return window['go']['main']['App']['AnalyzeProject'](arg1);
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function ExportLogs(arg1, arg2) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2);
}

export function GetAllServerStates() {
  return window['go']['main']['App']['GetAllServerStates']();
}

export function GetListeningPorts() {
  return window['go']['main']['App']['GetListeningPorts']();
}

export function GetProcessCommand(arg1, arg2) {
  return window['go']['main']['App']['GetProcessCommand'](arg1, arg2);
}

export function GetRecentLogs(arg1, arg2) {
  return window['go']['main']['App']['GetRecentLogs'](arg1, arg2);
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function KillByPort(arg1) {
  return window['go']['main']['App']['KillByPort'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListWSLDistros() {
  return window['go']['main']['App']['ListWSLDistros']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveServer(arg1, arg2) {
  return window['go']['main']['App']['RemoveServer'](arg1, arg2);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function ResyncServerPort(arg1) {
  return window['go']['main']['App']['ResyncServerPort'](arg1);
}

export function ScanSystemPorts() {
  return window['go']['main']['App']['ScanSystemPorts']();
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function SuggestFreePort(arg1) {
  return window['go']['main']['App']['SuggestFreePort'](arg1);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2);
}
