// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {project} from '../models';
import {ports} from '../models';

export function AddProject(arg1:string,arg2:string,arg3:any):Promise<config.Project>;

export function AddServer(arg1:string,arg2:config.Server):Promise<config.Server>;

export function AnalyzeProject(arg1:string):Promise<project.ProjectAnalysis>;

export function BrowseDirectory():Promise<string>;

export function ExportLogs(arg1:string,arg2:string):Promise<void>;

export function GetAllServerStates():Promise<Record<string, string>>;

export function GetListeningPorts():Promise<Array<number>>;

export function GetRecentLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetSystemStats():Promise<Record<string, any>>;

export function KillByPort(arg1:number):Promise<void>;

export function ListProjects():Promise<Array<config.Project>>;

export function ListWSLDistros():Promise<Array<string>>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveServer(arg1:string,arg2:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function ResyncServerPort(arg1:string):Promise<number>;

export function ScanSystemPorts():Promise<Array<ports.PortEntry>>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function SuggestFreePort(arg1:number):Promise<number>;

export function UpdateServer(arg1:string,arg2:config.Server):Promise<void>;
